force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Stores the data of each Employee</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Selectable_For_Employee__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <label>Requester</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Status_Value_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SAS_Request_Controller.cls
public with sharing class SAS_Request_Controller {

    @AuraEnabled(cacheable=true)
    public static List<Request__c> getMyRequests() {

        // Step 1: Get Employee for logged-in user
        Employee__c emp = [
            SELECT Id
            FROM Employee__c
            WHERE User__c = :UserInfo.getUserId()
            LIMIT 1
        ];

        // Step 2: Get Requests linked to that Employee
        return [
            SELECT Id, Name, Status__c, CreatedDate
            FROM Request__c
            WHERE 	Requester__c = :emp.Id
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled
    public static String createRequest(String requestType, String blockId, String groupName, String reason, String empId) {

        Map<String, Object> inputs = new Map<String, Object>{
            'varBlockId'      => blockId,
            'varGroupName'    => groupName,
            'varRequestType'  => requestType,
            'varReason'  => reason,
            'varRequesterId'  => empId
        };

        Flow.Interview.Submit_for_Approval_From_Autolaunched_Flow flow = new Flow.Interview.Submit_for_Approval_From_Autolaunched_Flow(inputs);

        flow.start();

        String requestId = (String)flow.getVariableValue('varCreatedRequestId');
       // System.assert(false, requestId);
        return requestId;
    }
}