force-app/main/default/objects/Cycle__c/Cycle__c.object-meta.xml
<CustomObject>
    <label>Cycle</label>
    <nameField>
        <label>Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cycle__c/fields/Current_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Current_Schedule__c</fullName>
    <label>Current Schedule</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cycle__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups_Picklist_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Stores the data of each Employee</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups_Picklist_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/WfoFinderMonth.cls
public with sharing class WfoFinderMonth {
    public static Map<String, Boolean> findWfoDaysForAMonth(String empId, Date inpDate){
		
        Map<String, Boolean> wfoDaysMap = new Map<String, Boolean>();

        Date todayDate = Date.today();
        Date todayDateWeekStartDate = todayDate.toStartOfWeek();
        //System.debug(todayDateWeekStartDate);

        Date weekStartDateOfTheCurrentMonth = inpDate.toStartOfMonth().toStartOfWeek();
        //System.debug(weekStartDateOfTheCurrentMonth);

        Integer daysBetween =  Math.abs(todayDateWeekStartDate.daysBetween(weekStartDateOfTheCurrentMonth));
        //System.debug(daysBetween);
        
        Integer noOfWeeksBetween = daysBetween/7;
        //System.debug('No of weeks between is ' + noOfWeeksBetween );

        Date monthStartDate = inpDate.toStartOfMonth();
        Integer year = monthStartDate.year();
        Integer month = monthStartDate.month();
        Integer numOfDays = Date.daysInMonth(year, month);
        Date startDate = monthStartDate;
        Date weekStartDate = weekStartDateOfTheCurrentMonth;
        
        Employee__c emp = [SELECT Id, Group__c FROM Employee__c WHERE Id = :empId];
        
        if(emp.Group__c == 'X' || emp.Group__c == 'Y' ){
            for(Integer i=0; i<numOfDays; i++){
                String nameOfTheDay = SAS_Day_Finder_Of_The_Week.getDayName(startDate);
                if(nameOfTheDay == 'Saturday' || nameOfTheDay == 'Sunday'){
                    wfoDaysMap.put(String.valueOf(startDate), false);
                }else{
                    wfoDaysMap.put(String.valueOf(startDate), true);
                }
                startDate += 1; 
            }
            //System.debug(wfoDaysMap);
            return wfoDaysMap;
        }else{
            Cycle__c cyc = [SELECT Id, Name, Current_Schedule__c FROM Cycle__c WHERE Group__c = :emp.Group__c];
            List<Cycle__c> cycList = [SELECT Id,Name,Current_Schedule__c FROM Cycle__c ORDER BY Name ASC];
            
            // create a list to store the names
            List<String> cycleNameList = new List<String>();
            for (Cycle__c c : cycList) {
                cycleNameList.add(c.Name);
            }
    
            Integer numOfCycles = cycList.size();
            Integer mod =  Math.mod((noOfWeeksBetween), numOfCycles);  
            Integer index = cycleNameList.indexOf(cyc.Name);
            
            Cycle__c currentCycle;
            if(inpDate < todayDate ){
                currentCycle = cycList[Math.mod((index - mod + numOfCycles), numOfCycles)];
            }else{
                currentCycle = cycList[Math.mod((index + mod), numOfCycles)];
            }
            index = cycleNameList.indexOf(currentCycle.Name);
            //System.debug('the index is '+ index);
    
            Set<String> wfoDays = new Set<String>(currentCycle.Current_Schedule__c.split(';'));
            //System.assert(false,weekDays);
    
            
            
            for(Integer i=0; i<numOfDays; i++){
    
                //System.debug('day' +i);
                String nameOfTheDay = SAS_Day_Finder_Of_The_Week.getDayName(startDate);
                //System.debug('The day is ' +nameOfTheDay);
                //System.debug('The date is ' +startDate);
                //System.debug('The start date of the week  is ' +weekStartDate);
                
                if(wfoDays.contains(nameOfTheDay)){
                    wfoDaysMap.put(String.valueOf(startDate), true);
                    //System.debug('Work from office on ' + nameOfTheDay);
                }else {
                    wfoDaysMap.put(String.valueOf(startDate), false);
                    //System.debug('Work from home on ' + nameOfTheDay);
                }
                startDate += 1;
                if(startDate > weekStartDate + 7){
                    index += 1;
                    weekStartDate += 7;
                    currentCycle = cycList[Math.mod((index), numOfCycles)];
                    //System.debug('The current cycle is ' + currentCycle);
                    wfoDays = new Set<String>(currentCycle.Current_Schedule__c.split(';'));
                }
                //System.debug(index);
      
            }
    
            return wfoDaysMap;
        }

        
    
    }

}