force-app/main/default/objects/Cycle__c/Cycle__c.object-meta.xml
<CustomObject>
    <label>Cycle</label>
    <nameField>
        <label>Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cycle__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups_Picklist_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SAS_Test_Cycle_Group_Rotator.cls
@IsTest
public class SAS_Test_Cycle_Group_Rotator {

    @IsTest
    public static void givenMultipleCycles_WhenRotateGroups_ThenGroupsAreRotated() {

        Cycle__c c1 = new Cycle__c(Name = 'Cycle 1', Group__c = 'A');
        Cycle__c c2 = new Cycle__c(Name = 'Cycle 2', Group__c = 'B');
        
        Database.insert(new List<Cycle__c>{ c1, c2 },false);

        CycleGroupRotator.rotateGroups();

        List<Cycle__c> updatedCycles = [SELECT Name, Group__c FROM Cycle__c ORDER BY CreatedDate];

        System.assertEquals('B', updatedCycles[0].Group__c);
        System.assertEquals('A', updatedCycles[1].Group__c);
    }

    @IsTest
    static void givenSingleCycle_WhenRotateGroups_ThenNoChangeOccurs() {

        Cycle__c c = new Cycle__c(Name = 'Cycle 1', Group__c = 'A');
        Database.insert(c, false);

        Test.startTest();
        CycleGroupRotator.rotateGroups();
        Test.stopTest();

        Cycle__c updated = [SELECT Group__c FROM Cycle__c WHERE Id = :c.Id];

        System.assertEquals('A', updated.Group__c);
    }
}