force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Stores the data of each Employee</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Block</label>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Stores the email address of the employee</description>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups_Picklist_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Selectable_For_Employee__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SAS_Employee_Controller.cls
public with sharing class SAS_Employee_Controller {
    @AuraEnabled(cacheable=true)
    public static Employee__c getLoggedInEmployeeId() {
        Id userId = UserInfo.getUserId();

        Employee__c emp = [
            SELECT Id, Block__c, Group__c 
            FROM Employee__c 
            WHERE User__c = :userId
            LIMIT 1
        ];

        return emp;
    }

    @AuraEnabled(cacheable=true)
    public static List<Employee__c> getEmployeesByGroup(String groupName) {
        if (String.isBlank(groupName)) {
            return new List<Employee__c>();
        }

        return [
            SELECT Id, Name, Email__c, Group__c, Block__r.Name
            FROM Employee__c
            WHERE Group__c = :groupName
        ];
    }

    @AuraEnabled()
    public static List<Employee__c> getEmployeesByTeam(String teamName) {
        if (String.isBlank(teamName)) {
            return new List<Employee__c>();
        }

        return [
            SELECT Id, Name, Email__c, Group__c, Block__r.Name
            FROM Employee__c
            WHERE Team__c = :teamName
        ];
    }

    @AuraEnabled()
    public static List<Employee__c> getEmployeesByName(String empName) {
        if (String.isBlank(empName)) {
            return new List<Employee__c>();
        }

        return [
            SELECT Id, Name, Email__c, Group__c, Block__r.Name
            FROM Employee__c
            WHERE Name LIKE :('%' + empName + '%')
        ];
    }


    @AuraEnabled(cacheable=true)
    public static Integer getAvailableSeats(String groupName, String blockId) {
       /* if (String.isBlank(groupName) || blockId == null) {
            return 0;
        }*/
        // Daily groups
        // Prepare input variables for Flow
        Map<String, Object> flowInputs = new Map<String, Object>();
        
        flowInputs.put('varBlockId',blockId );
        flowInputs.put('varGroupName',groupName );

        // Invoke the autolaunched Flow
        Flow.Interview.Get_Available_Seats flowInstance = new Flow.Interview.Get_Available_Seats(flowInputs);

        flowInstance.start();
        Decimal count = (Decimal)flowInstance.getVariableValue('varAvailableSeats');
        Integer intCount = (Integer)count;
        //System.assert(false,intCount );

        // Return output variable from Flow
		System.debug(intCount);
        return intCount;
        
    }

    @AuraEnabled
    public static void bulkUpdateEmployees(List<Id> employeeIds, Id blockId, String groupName) {
        List<Employee__c> toUpdate = new List<Employee__c>();

        for (Id empId : employeeIds) {
            Employee__c e = new Employee__c(
                Id = empId,
                Block__c = blockId,
                Group__c = groupName
            );
            toUpdate.add(e);
        }

        if (!toUpdate.isEmpty()) {
            update toUpdate;
        }
    }
}